_wandb:
    value:
        cli_version: 0.27.0
        e:
            3wc5s1uvvr3bdvryqbmco8xtzhqb387d:
                codePath: /home/vilota/mingjie/dinov3/scripts/dinov3_blur_detection_trainer_v5.ipynb
                codePathLocal: dinov3_blur_detection_trainer_v5.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1142152196096"
                        used: "361374371840"
                email: mhu005@e.ntu.edu.sg
                executable: /home/vilota/anaconda3/envs/dinov3/bin/python
                git:
                    commit: e647a39319a9d6cf03621f7cb88c1ce844997a0f
                    remote: https://github.com/vilota-dev/dinov3.git
                host: vilota
                memory:
                    total: "32700198912"
                os: Linux-6.17.0-29-generic-x86_64-with-glibc2.39
                program: /home/vilota/mingjie/dinov3/scripts/dinov3_blur_detection_trainer_v5.ipynb
                python: CPython 3.11.15
                root: /home/vilota/mingjie/dinov3/scripts
                startedAt: "2026-06-02T02:52:46.762950Z"
                writerId: 3wc5s1uvvr3bdvryqbmco8xtzhqb387d
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.15
            "5": 0.27.0
            "8":
                - 1
            "12": 0.27.0
            "13": linux-x86_64
architecture:
    value: dinov3_vith16plus
